openapi: 3.0.3
info:
    title: Test DevOz Developer Jr.
    description: DevOz Test API Documentation for Developer Jr.
    contact:
        name: API Support
        email: breno.jose.coelho@gmail.com
    version: 1.0.2
servers:
    - url: https://localhost:4000
      description: Route to run the API
      variables:
          basePath:
              default: /api/v1
tags:
    - name: users
      description: Operações do Usuario.
paths:
    /users:
        get:
            tags:
                - users
            responses:
                "200":
                    description: Retorna todos os usuários cadastrados.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/getAllUsers"
                            examples:
                                objectExample:
                                    $ref: "#/components/examples/getAllExample"                             
        post:
            tags:
                - users
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/user"
            responses:
                "201":
                    description: User created successfully
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/user"
                "400":
                    description: Age under 18
    /users/{name}:
        get:
            tags:
                - users
            parameters:
                - in: path
                  description: O nome tem que ser no formato string sem acentos e e deve ser igual ao que esta cadastrado.
                  name: name
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: Retorna todos usuarios com o nome passado por parametro.
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/user"
                "404":
                    description: User not found
        delete:
            tags:
                - users
            parameters:
                - in: path
                  description: O nome tem que ser no formato string sem acentos e deve ser igual ao que esta cadastrado.
                  name: name
                  required: true
                  schema:
                      type: string
            responses:
                "200":
                    description: User deleted successfully
                "404":
                    description: User not found
    /users/{nameid}:
        put:
            tags:
                - users
            description: Editar o usuario.
            parameters:
                - in: path
                  description: O nome tem que ser no formato string sem acentos e deve ser igual ao que esta cadastrado.
                  name: nameid
                  required: true
                  schema:
                      type: string
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/user"
            responses:
                "200":
                    description: User changed successfully
                "404":
                    description: User not found
components:
    schemas:
        user:
            type: object
            required:
                - id
                - name
                - email
                - age
            properties:
                _id:
                    description: >-
                        ID do usuario é inserido automaticamente a cada insert
                    type: string
                    example: 615ce7b9abdf68d6a3f173e2
                name:
                    description: Nome do usuario
                    type: string
                    example: Breno
                email:
                    description: Email do usuario
                    type: string
                    example: breno.jose.coelho@gmail.com
                age:
                    description: Idade do usuario, deve ser maior ou igual a 18
                    type: number
                    example: "19"
        getAllUsers:
            type: array
            description: Array com todos os usuarios que foi cadastrado no banco de dados
            items:
                type: object
    examples:
        usersExample:
            value:
                _id: "62ed99d6d8716db310e3ed67"
                name: "Breno"
                email: "breno@devoz.com.br"
                age: 19
        getAllExample:
            value:
            -   _id: "62ed99d6d8716db310e3ed69"
                name: "Vinicius"
                email: "vinicius@devoz.com.br"
                age: 28
            -   _id: "62ed99d6d8716db310e3ed6b"
                name: "Caio"
                email: "caio@devoz.com.br"
                age: 22
            -   _id: "62ed99d6d8716db310e3ed6f"
                name: "Beatriz"
                email: "beatriz@devoz.com.br"
                age: 18  
            -   _id: 615ce7c5abdf68d6a3f173e4
                name: julia
                email: julia.raupp@devoz.com.br
                age: 27
